package cas

import grails.converters.JSON
import groovyx.net.http.HTTPBuilder

class ExamplesController {

    def index() { }

    def getFacultyData(){
        Faculty faculty;

        Map query = [:];
        String url = "http://ist.rit.edu/"
        String path = "api/people"

        def http = new HTTPBuilder(url)

        http.ignoreSSLIssues()
        http.get( path : path, query : query ) { resp, reader ->
            reader.faculty.each{
                //"it" was generated by .each
                if(it.username){
                    faculty = Faculty.findByUsername(it.username)
                    if(!faculty){
                        faculty = new Faculty(username: it.username, name: it.name, tagline: it.tagline, imagePath: it.imagePath, title: it.title,
                                interestArea: it.interestArea, office: it.office, website: it.website, phone: it.phone, email: it.email, twitter: it.twitter, facebook: it.facebook)

                        faculty.save(flush: true)
                    }
                }
                else {
                    println("invalid data at: ")
                    println it
                }
            }
            render("OK")
        }
    }

    def createDropdown(){
        def faculty = Faculty.findAll()
        render (template: "facultySelect", model: [faculty: faculty])
    };

    def getSpecificData(String username){
        def facultyMember = Faculty.findByUsername(username)
        println 1
        render (template: "facultyData", model: [facultyMember: facultyMember])
    }
}
